services:
  - type: web
    name: learning-progress-tracker
    env: node
    plan: free
    buildCommand: npm install && npm run build:css-prod
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
