services:
  - type: web
    name: learning-progress-tracker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: learning-tracker-db
          property: connectionString

databases:
  - name: learning-tracker-db
    databaseName: learning_tracker
    user: learning_user
    plan: free
